version: '3.8'
services:
  app:
    # Allows container to monitor source code for changes
    # and will recompile if changes are detected
    volumes:
      - .:/app:delegated
    container_name: rove-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: api.Dockerfile    
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env/app.env
