version: '3.8'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: database
    volumes:
        - pg-data:/var/lib/postgresql/data
    env_file:
      - .env/db.env
    ports:
      - "5432:5432"

  app:
    container_name: rove-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile    
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env/app.env

volumes:
  pg-data: