version: '3.8'
services:
  db:
    image: postgis/postgis:latest
    restart: unless-stopped
    container_name: database
    volumes:
        - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  pg-data: