# fly.toml app configuration file generated for rove-api on 2024-04-21T17:23:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rove-web-api'
primary_region = 'atl'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  DATABASE_SERVER_NAME = 'ep-tight-feather-a5x7dev0-pooler.us-east-2.aws.neon.tech'
  DATABASE_URL = 'postgresql://rove-prod_owner:MtYHc5hPCnB2@ep-tight-feather-a5x7dev0-pooler.us-east-2.aws.neon.tech/rove-prod?sslmode=require'
  GOOGLE_MAPS_API_KEY = 'AIzaSyDMyw_MSd2aE7hzWY-QgHg8AC5gsa2gJO8'
  GUARDIAN_SECRET_KEY = '458wrmzZh6cpi1EBdgwmS3ESUSdNs2eIJhj+eQVRKSJPTje4MkAPA0c/iiulGcKr'
  MIX_ENV = 'prod'
  PHX_HOST = 'rove-web-api.fly.dev'
  PORT = '4000'
  SECRET_KEY_BASE = '0wYlyS3kgMxkmIFB1XbRSyWpJpRAIFMqvK/hLjwCXhMqW9FBg3xOxP2YdDF7Niig'
  SIGNING_SALT = 'ERe092m'

[http_service]
  internal_port = 4000 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
