# fly.toml file generated for your-app-name on Fly
app = "rove-web-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  # Define your environment variables here, if needed
  # PORT="8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # the time to wait before starting health checks
    interval = "15s"
    timeout = "2s"
